main/urls.py
from django.urls import path
from main import views
from main.views import create_product_flutter, edit_product, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, create_product_ajax
from django.conf.urls.static import static
from django.conf import settings
from main.views import register, login_user, logout_user, delete_product

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('', views.show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-ajax/', create_product_ajax, name='create_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_mood_flutter'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nai_express/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', register, name='register'),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    image = models.ImageField(upload_to='images/')
    availability = models.CharField(max_length=50, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')])
    discount = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    def __str__(self):
        return self.name  

class OwnerInfo(models.Model):
    name = models.CharField(max_length=100)
    class_name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.html import strip_tags


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "stock", "image", "availability", "discount"]

    # Menggunakan pendekatan yang membuat lebih mudah untuk kustomisasi

    name = forms.CharField(
        max_length=100, 
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'})
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Product Description'}),
        required=True
    )
    price = forms.DecimalField(
        min_value=0,
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price'})
    )
    stock = forms.IntegerField(
        min_value=0,
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock'})
    )
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
    )
    availability = forms.ChoiceField(
        choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')],
        required=True,
        widget=forms.Select(attrs={'class': 'custom-select'})
    )
    discount = forms.IntegerField(
        min_value=0,
        max_value=100,
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Discount'})
    )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        cleaned_name = strip_tags(name)
        if not cleaned_name:
            raise forms.ValidationError("Field name tidak boleh kosong setelah dibersihkan.")
        return cleaned_name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        cleaned_description = strip_tags(description)
        if not cleaned_description:
            raise forms.ValidationError("Field description tidak boleh kosong setelah dibersihkan.")
        return cleaned_description
    


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email address',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        })
    )

main/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

import json
from django.http import JsonResponse

@login_required(login_url='/login')
def show_main(request):
    # products = Product.objects.filter(user=request.user)
    last_login = request.COOKIES.get('last_login')

    context = {
        'website_title': 'Nai Express📦',
        'name': request.user.username,
        'class_name': 'PBP C',
        # 'products': products, 
        'last_login': last_login,

    }

    return render(request, "main.html", context)


def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)  
            product.user = request.user  
            product.save() 
            return redirect('main:show_main') 
        else:
            return render(request, "create_product.html", {'form': form})
    else:
        form = ProductForm()

    return render(request, "create_product.html", {'form': form})

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
      else:
            messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:show_main'))
    else:
        form = ProductForm(instance=product)

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id);
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))


@csrf_exempt
@require_POST
def create_product_ajax(request):
    name = strip_tags(request.POST.get("name"))  
    description = strip_tags(request.POST.get("description"))  

    # Buat dan simpan produk baru tanpa membersihkan data saat testing
    new_product = Product(
        name=name, 
        description=description,
        price=request.POST.get("price"),
        stock=request.POST.get("stock"),
        availability=request.POST.get("availability"),
        image=request.FILES.get("image"),
        user=request.user
    )
    
    new_product.save()

    return HttpResponse(b"CREATED", status=201)


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,  # Pastikan `user` diambil dari `request.user`
            name=data.get("name", ""),  # Pastikan ada nilai default jika kosong
            description=data.get("description", ""),
            price=data.get("price", "0.0"),
            stock=data.get("stock", 0),
            image=data.get("image", ""),  # Jika ada field image
            availability=data.get("availability", "In Stock"),
            discount=data.get("discount", "0.0"),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_product.html
{% comment %} <section class="vh-100" style="background-color: #f5f5f5;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-4 text-black">
            <div class="text-center">
              <!-- Nama Produk -->
              <h4 class="mb-4">{{ product.name }}</h4>
              
              <!-- Gambar Produk -->
              <img src="{{ product.image.url }}" alt="{{ product.name }}"
                   class="img-fluid mb-4"
                   style="width: 100%; border-radius: 15px;">
            </div>

            <!-- Harga dan Diskon -->
            <div class="d-flex justify-content-between mb-4">
              <p class="fw-bold text-primary mb-0" style="font-size: 1.5rem;">
                ${{ product.price }}
              </p>
              {% if product.discount %}
              <p class="text-danger mb-0">
                Discount: {{ product.discount }}%
              </p>
              {% endif %}
            </div>

            <!-- Deskripsi Produk -->
            <div class="mb-4">
              <p>{{ product.description }}</p>
            </div>

            <!-- Ketersediaan Stok -->
            <div class="mb-4">
              <p class="text-muted">
                Availability: {{ product.availability }}
              </p>
            </div>

            <!-- Tombol Edit dan Delete -->
            <div class="d-flex justify-content-between">
              <!-- Tombol Edit -->
              <a href="{% url 'main:edit_product' product.id %}" class="btn btn-outline-primary btn-rounded btn-lg w-45 mb-2">
                <i class="fas fa-edit me-2"></i>Edit
              </a>
              
              <!-- Tombol Delete -->
              <form method="POST" action="{% url 'main:delete_product' product.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-rounded btn-lg w-45 mb-2" onclick="return confirm('Are you sure you want to delete this product?');">
                  <i class="fas fa-trash me-2"></i>Delete
                </button>
              </form>
            </div>

            <!-- Info Penjual -->
      

            <!-- Comments Section -->
          
          </div>
        </div>
      </div>
    </div>
  </div>
</section> {% endcomment %}


<div class="container mt-5 mb-5">
  <div class="d-flex justify-content-center row">
    <div class="col-md-10">
      <div class="row p-2 bg-white border rounded mt-2">
        <!-- Product Image -->
        <div class="col-md-3 mt-1 align-self-center">
          <img class="img-fluid img-responsive rounded product-image" 
               src="{{ product.image.url }}" 
               alt="{{ product.name }}" 
               style="width: 100%; height: 300px; object-fit: cover; border-radius: 15px;">
        </div>

        <!-- Product Info (centered vertically) -->
        <div class="col-md-6 d-flex flex-column justify-content-center">
          <div>
            <h5>{{ product.name }}</h5>
            <div class="mt-1 mb-1 spec-1">
              <span id="short-description">
                {{ product.description|truncatewords:30 }}...
              </span>
              <span id="full-description" style="display:none;">
                {{ product.description }}
              </span>
              <a href="javascript:void(0);" id="read-more" onclick="toggleDescription()">Read more</a>            </div>
          </div>
        </div>

        <!-- Product Actions (Price/Discount/Stock Indicator and Edit/Delete) -->
        <div class="align-items-center align-content-center col-md-3 border-left mt-1">
          <!-- Price, Discount, and Stock -->
          <div class="d-flex flex-column">
            <!-- Final Price -->
            <h4 class="fw-bold">Rp{{ product.price|floatformat:0 }}</h4>

            <!-- Original Price (striked through) and Discount Percentage -->
            <div class="d-flex align-items-center">
              <span class="ms-2 text-danger">Discount : {{ product.discount }}%</span>
            </div>

            <!-- Stock Indicator -->
            <div class="mt-2">
              {% if product.stock <= 5 %}
              <!-- Low stock -->
              <div class="progress" style="height: 5px;">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small class="text-muted">Segera Habis</small>
              {% else %}
              <!-- Stock available -->
              <div class="progress" style="height: 5px;">
                <div class="progress-bar bg-success" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <small class="text-muted">Stok Tersedia</small>
              {% endif %}
            </div>
          </div>

          <!-- Edit and Delete Buttons -->
          <div class="d-flex flex-column mt-4">
            <!-- Edit Button -->
            <a href="{% url 'main:edit_product' product.id %}" class="btn btn-primary btn-sm mb-2">Edit</a>
            <!-- Delete Button -->
            <a href="{% url 'main:delete_product' product.id %}" class="btn btn-danger btn-sm">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

main/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ website_title }} {% endblock %}

{% block meta %}
    {% include 'navbar.html' %}
    <meta name="description" content="This is a product page for {{ website_title }}" />
    <script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>

{% endblock %}

{% block header %}
    Welcome to {{ website_title }}
{% endblock %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="service-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Nai Express</h1>
        <p class="lead">No other service is like Nai Express—because when others say 'nah,' we say 'Nai!' 🚀</p>
        <p class="lead">Nai straight at your service, faster than you can blink!</p>
    </div>

    <hr style="border-top: 1px solid #bbb; width: 80%; margin: 20px auto" />

    <div class="container">
        <!-- Product Cards -->
        <div id="product_cards"></div>

        <!-- Bootstrap Modal for Product Creation -->
        <div class="modal fade" id="crudModal" tabindex="-1" aria-labelledby="crudModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <!-- Modal header -->
                    <div class="modal-header">
                        <h5 class="modal-title" id="crudModalLabel">Add New Product</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <!-- Modal body -->
                    <div class="modal-body">
                        <form id="productForm" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="form-label">Product Name</label>
                                <input type="text" id="name" name="name" class="form-control" placeholder="Enter product name" required>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea id="description" name="description" class="form-control" rows="3" placeholder="Enter product description" required></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="price" class="form-label">Price</label>
                                <input type="number" id="price" name="price" class="form-control" placeholder="Enter product price" required>
                            </div>
                            <div class="mb-3">
                                <label for="stock" class="form-label">Stock</label>
                                <input type="number" id="stock" name="stock" class="form-control" placeholder="Enter stock quantity" required>
                            </div>
                            <div class="mb-3">
                                <label for="image" class="form-label">Product Image</label>
                                <input type="file" id="image" name="image" class="form-control">
                            </div>
                            <div class="mb-3">
                                <label for="availability" class="form-label">Availability</label>
                                <select id="availability" name="availability" class="form-select">
                                    <option value="In Stock">In Stock</option>
                                    <option value="Out of Stock">Out of Stock</option>
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="discount" class="form-label">Discount (%)</label>
                                <input type="number" id="discount" name="discount" class="form-control" placeholder="Enter discount percentage">
                            </div>
                        </form>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" form="productForm" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>

        <br />
        <div class="button-group">
            <!-- Add New Product Button -->
            <a href="{% url 'main:create_product' %}"  class="btn btn-primary btn-sm d-flex align-items-center shadow-sm w-100 mb-2" style="border-radius: 30px;">
              <i class="fas fa-box-open me-2"></i> Add Product
          </a>


            <button data-bs-toggle="modal" data-bs-target="#crudModal" class="btn btn-primary btn-sm d-flex align-items-center shadow-sm w-100 mb-2" style="border-radius: 30px;">
                <i class="fas fa-box-open me-2"></i> Add Product by create_product_ajax
            </button>
        </div>
    </div>
</div>

<script>
async function getProducts() {
    return fetch("{% url 'main:show_json' %}")
        .then((res) => res.json())
        .catch((error) => console.log("Error fetching products: ", error));
}

async function refreshProducts() {
    // Clear the existing content
    document.getElementById("product_cards").innerHTML = "";
    document.getElementById("product_cards").className = "";

    // Fetch the list of products
    const products = await getProducts();
    let htmlString = "";
    let classNameString = "";

    if (products.length === 0) {
        classNameString = "d-flex flex-column align-items-center justify-content-center min-vh-50 p-4";
        htmlString = `
            <div class="d-flex flex-column align-items-center justify-content-center min-vh-50 p-4">
                <img src="{% static 'images/sad.png' %}" alt="Sad face" class="w-25 h-25 mb-4"/>
                <p class="text-center text-muted mt-4">No products found.</p>
            </div>
        `;
    } else {
        classNameString = "row g-4";
        products.forEach((product) => {
          const name = DOMPurify.sanitize(product.fields.name);
          const description = DOMPurify.sanitize(product.fields.description);
            htmlString += `
                <div class="container mt-5 mb-5">
                    <div class="d-flex justify-content-center row">
                        <div class="col-md-10">
                            <div class="row p-2 bg-white border rounded mt-2">
                                <div class="col-md-3 mt-1 align-self-center">
                                    <img class="img-fluid img-responsive rounded product-image"
                                         src="${product.fields.image}"
                                         alt="${name}"
                                         style="width: 100%; height: 300px; object-fit: cover; border-radius: 15px;">
                                </div>
                                <div class="col-md-6 d-flex flex-column justify-content-center">
                                    <div>
                                        <h5>${name}</h5>
                                        <div class="mt-1 mb-1 spec-1">
                                            <span>${description}...</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                                    <div class="d-flex flex-column">
                                        <h4 class="fw-bold">Rp${product.fields.price}</h4>
                                        <div class="d-flex align-items-center">
                                            <span class="ms-2 text-danger">Discount: ${product.fields.discount}%</span>
                                        </div>
                                        <div class="mt-2">
                                            ${product.fields.stock <= 5 ? `
                                                <div class="progress" style="height: 5px;">
                                                    <div class="progress-bar bg-danger" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                                <small class="text-muted">Segera Habis</small>
                                            ` : `
                                                <div class="progress" style="height: 5px;">
                                                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                                <small class="text-muted">Stok Tersedia</small>
                                            `}
                                        </div>
                                    </div>
                                    <div class="d-flex flex-column mt-4">
                                        <a href="/edit-product/${product.pk}" class="btn btn-primary btn-sm mb-2">Edit</a>
                                        <a href="/delete/${product.pk}" class="btn btn-danger btn-sm">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            `;
        });
    }
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
}

refreshProducts();

function createProduct() {
    const formData = new FormData(document.querySelector('#productForm'));

    fetch("{% url 'main:create_product_ajax' %}", {
        method: "POST",
        body: formData,
    })
    .then(response => {
        if (response.ok) {
            refreshProducts();
            // Close modal after success
            document.getElementById("productForm").reset();
            document.querySelector("[data-bs-dismiss='modal']").click();
        } else {
            console.log("Failed to create product.");
        }
    })
    .catch(error => console.log("Error creating product:", error));

    return false;
}

document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    createProduct();
});
</script>

{% endblock %}

main/templates/navbar.html
{% load static %}
  <link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
  rel="stylesheet"
/>

<nav class="navbar-custom navbar navbar-expand-lg navbar-light sticky-top py-1">
  <div class="container-fluid d-flex flex-column flex-md-row justify-content-between align-items-center">
    <a class="navbar-brand d-flex align-items-center py-2" href="#">
      <img
        src="{% static 'images/shopping.png' %}"
        alt="Shopping Icon"
        width="24"
        height="24"
        class="d-block mx-auto"
      />
      <span class="ml-2 font-weight-bold">Nai Express</span>
    </a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:show_main' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> {% endcomment %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'main:create_product' %}">Create Product</a></li>
            <li><a class="dropdown-item" href="{% url 'main:show_main' %}">Show Product</a></li>
            {% comment %} <li><hr class="dropdown-divider" /></li> {% endcomment %}
            {% comment %} <li><a class="dropdown-item" href="#">Something else here</a></li> {% endcomment %}
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text mr-3">Welcome, {{ user.username }}!</span>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-danger" href="{% url 'main:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="{% url 'main:login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>